### ISSUE TITLE
Pre-training dataset release

### ISSUE THREAD

**Issue by rtanaka-lab** [due-benchmark/baselines#1]
Thank you for sharing great work!  I was wondering if there is an expected date on when you will be releasing your pre-training dataset, some code for crawling, or download URL? 
To be fair with comparing your baseline model (T5+2D+U),  please share above information.

**Comment by Borchmann** [comment]
The repository now contains the list of documents we used for unsupervised training and script to download them from the Industry Documents library. You can find these in the `downloaders/industry_documents` directory.

Additionally, the output of Tesseract OCR that we used during the unsupervised pretraining is now available at https://applica-public.s3.eu-west-1.amazonaws.com/due/datasets/IndustryDocuments.tar.gz

As the dataset contains ~920k documents, it seems the information on the pretraining dataset size in the paper (~480k) was incorrect.

Thank you for this suggestion, and sorry for the delayed response. Please let us know if there’s anything else we can do.

**Comment by rtanaka-lab** [comment]
Thank you for sharing!

**Comment by xienian87** [comment]
@rtanaka-lab Do you have the code for T5 baseline pre-training?

**Comment by XinnuoXu** [comment]
> The repository now contains the list of documents we used for unsupervised training and script to download them from the Industry Documents library. You can find these in the `downloaders/industry_documents` directory.
> 
> Additionally, the output of Tesseract OCR that we used during the unsupervised pretraining is now available at https://applica-public.s3.eu-west-1.amazonaws.com/due/datasets/IndustryDocuments.tar.gz
> 
> As the dataset contains ~920k documents, it seems the information on the pretraining dataset size in the paper (~480k) was incorrect.
> 
> Thank you for this suggestion, and sorry for the delayed response. Please let us know if there’s anything else we can do.

Got this error when downloading the data:
```
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```
@Borchmann

**Comment by XinnuoXu** [comment]
> @rtanaka-lab Do you have the code for T5 baseline pre-training?

@Borchmann I have the same request.
